#!/usr/bin/env bash
#install nignx -- redirection
apt-get update -y
apt-get install -y nginx
chown -R "$USER":"$USER" /var/www
chown -R "$USER":"$USER" /etc/nginx/
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
                add_header X-Served-By \$hostname;
        }

        location /redirect_me{
            return 301 https://www.facebook.com/sescozahmed/;
        }
        error_page 404 /404.html;
        location /404.html {
            root /var/www/html;
        }

}" | sudo tee /etc/nginx/sites-available/default > /dev/null
service nginx restart
