#!/usr/bin/env bash
#custom
apt-get update -y
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "/listen 80 default_server;/a \\\tadd_header X-Served-By $(hostname);" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server;/a \\\terror_page 404 /404.html; location = /404.html { root /usr/share/nginx/html; internal;}" /etc/nginx/sites-available/default
sed -i "/listen 80 default_server/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
service nginx restart
