#!/usr/bin/env bash
#custom http response
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location / {
            # First attempt to serve request as file, then
            # as directory, then fall back to displaying a 404.
	    add_header X-Served-By \$hostname;
            try_files $uri $uri/ =404;
    }
    location /redirect_me{
            return 301 https://www.facebook.com/sescozahmed/;
    }
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
