#!/usr/bin/env bash
#custom
sudo apt-get -y update
sudo apt-get -y install haproxy
sed -i "\$a\nfrontend my_frontend\n\tbind *80\n\tmode http\n\tdefault_backend my_backend\n" /etc/haproxy/haproxy.cfg
sed -i "\$a\nbackend my_backend\n\tbalance roundrobin\n\tserver web-01 54.209.141.133:80 check\n\tserver web-02 100.26.221.3:80 check\n" /etc/haproxy/haproxy.cfg
echo "ENABLED=1" >> /etc/default/haproxy
service haproxy restart
