#!/usr/bin/env bash
#fixing symbolic in site-enbaled
sudo service nginx stop
sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx start
