#!/usr/bin/env bash
# script print best school 10 times
hours=0
minutes=1
while [ $hours -le 12 ]
do
	echo "Hour: $hours"
	minutes=$((1))
	while [ $minutes -le 59 ]
	do
		echo $minutes
		minutes=$((minutes+1))
	done
	hours=$((hours+1))
done
