#!/usr/bin/env bash
#run nginx under specific user

sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
sudo -u nginx service nginx restart
